/**
 * Client-side mock data — mirrors sample_data JSON files.
 * Used as fallback when the backend is unreachable.
 */
import { Incident, Alert, Shelter, Resource, ResourceRequest } from "@/types";

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-001", type: "flood",
    title: "Flash Flood — Westlands Underpass",
    description: "Severe waterlogging at Westlands underpass. Three vehicles submerged. Rising water levels blocking main artery.",
    severity: "critical", status: "active",
    lat: -1.2641, lng: 36.7988, location_name: "Westlands, Nairobi",
    reporter_name: "Jane Wambui", affected_count: 45,
    timestamp: "2026-06-27T06:15:00Z", ai_category: "Natural Disaster / Flooding",
    ai_confidence: 0.97, verified: true,
  },
  {
    id: "inc-002", type: "fire",
    title: "Building Fire — Kenyatta Avenue",
    description: "Multi-storey building on fire, 4th and 5th floors engulfed. Occupants trapped.",
    severity: "high", status: "active",
    lat: -1.2857, lng: 36.8183, location_name: "Kenyatta Avenue, CBD",
    reporter_name: "David Kariuki", affected_count: 120,
    timestamp: "2026-06-27T07:30:00Z", ai_category: "Structural Fire",
    ai_confidence: 0.95, verified: true,
  },
  {
    id: "inc-003", type: "medical",
    title: "Mass Casualty Event — Kibera Market",
    description: "Gas explosion at market stall. Multiple casualties reported. MSF team requested.",
    severity: "critical", status: "active",
    lat: -1.3143, lng: 36.7885, location_name: "Kibera Market, Nairobi",
    reporter_name: "Mercy Ochieng", affected_count: 38,
    timestamp: "2026-06-27T05:45:00Z", ai_category: "Medical Emergency / Mass Casualty",
    ai_confidence: 0.98, verified: true,
  },
  {
    id: "inc-004", type: "infrastructure",
    title: "Bridge Structural Damage — Eastlands",
    description: "Mathare footbridge showing signs of collapse after overnight rainfall.",
    severity: "high", status: "monitoring",
    lat: -1.2833, lng: 36.8667, location_name: "Mathare River Bridge, Eastlands",
    reporter_name: "Peter Mwangi", affected_count: 500,
    timestamp: "2026-06-27T04:20:00Z", ai_category: "Infrastructure Failure",
    ai_confidence: 0.89, verified: false,
  },
  {
    id: "inc-005", type: "civil_unrest",
    title: "Road Blockade — Ngong Road Junction",
    description: "Protest group blocking traffic at Ngong Road / Kilimani junction.",
    severity: "medium", status: "active",
    lat: -1.3100, lng: 36.7900, location_name: "Ngong Road Junction, Kilimani",
    affected_count: 2000,
    timestamp: "2026-06-27T08:00:00Z", ai_category: "Civil Unrest",
    ai_confidence: 0.88, verified: true,
  },
  {
    id: "inc-006", type: "contamination",
    title: "Water Contamination — Mathare Valley",
    description: "Residents reporting brown discoloured tap water. Multiple children showing symptoms.",
    severity: "high", status: "active",
    lat: -1.2573, lng: 36.8533, location_name: "Mathare Valley, Nairobi",
    reporter_name: "Grace Njeri", affected_count: 3500,
    timestamp: "2026-06-27T03:00:00Z", ai_category: "Public Health / Contamination",
    ai_confidence: 0.92, verified: true,
  },
  {
    id: "inc-007", type: "power_outage",
    title: "Grid Failure — Karen & Langata",
    description: "Complete power blackout affecting Karen, Langata, and Hardy areas.",
    severity: "low", status: "monitoring",
    lat: -1.3500, lng: 36.7100, location_name: "Karen, Nairobi",
    reporter_name: "Amos Gitonga", affected_count: 8000,
    timestamp: "2026-06-27T02:10:00Z", ai_category: "Infrastructure / Power",
    ai_confidence: 0.94, verified: true,
  },
  {
    id: "inc-008", type: "landslide",
    title: "Landslide Risk — Lavington Hill",
    description: "Soil erosion detected on Lavington escarpment after 3 days of heavy rain.",
    severity: "critical", status: "active",
    lat: -1.2850, lng: 36.7610, location_name: "Lavington Hill, Nairobi",
    reporter_name: "Susan Wanjiku", affected_count: 15,
    timestamp: "2026-06-27T07:00:00Z", ai_category: "Natural Disaster / Landslide",
    ai_confidence: 0.91, verified: false,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alrt-001",
    title: "FLASH FLOOD WARNING — Westlands & Parklands",
    message_en: "Flash flood warning issued for Westlands and Parklands areas. Avoid low-lying roads. Move to higher ground immediately.",
    message_sw: "Onyo la mafuriko ya ghafla kwa maeneo ya Westlands na Parklands. Epuka barabara za chini. Nenda mahali pa juu mara moja.",
    message_fr: "Alerte aux inondations soudaines pour les zones de Westlands et Parklands.",
    severity: "critical", category: "natural_disaster",
    issued_at: "2026-06-27T06:30:00Z", expires_at: "2026-06-27T18:30:00Z",
    affected_areas: ["Westlands", "Parklands", "Highridge"],
    source: "Kenya Meteorological Department", ai_generated: false, active: true,
    notification_channels: ["dashboard", "sms", "email"],
    delivery_status: { dashboard: "delivered", sms: "mock_sent", email: "mock_sent" },
    recommended_actions: ["Move to higher ground", "Avoid flooded roads", "Monitor Kenya Met alerts"],
    evacuation_guidance: "Proceed to Westlands Community Centre or Karen Evacuation Point.",
    public_safety_message: "Stay away from rivers and low-lying areas until further notice.",
    districts: ["Westlands", "Parklands"],
    radius_km: 10,
    lat: -1.2697,
    lng: 36.8134,
  },
  {
    id: "alrt-002",
    title: "MEDICAL EMERGENCY — Kibera Gas Explosion",
    message_en: "Mass casualty event in Kibera Market. All available medical personnel report to KNH Emergency.",
    message_sw: "Tukio la majeruhi mengi katika Soko la Kibera. Wafanyakazi wote wa matibabu waende KNH Dharura.",
    severity: "critical", category: "medical",
    issued_at: "2026-06-27T05:50:00Z",
    affected_areas: ["Kibera", "Langata"],
    source: "Nairobi County Health Department", ai_generated: false, active: true,
    notification_channels: ["dashboard", "sms", "whatsapp"],
    delivery_status: { dashboard: "delivered", sms: "mock_sent", whatsapp: "mock_sent" },
    recommended_actions: ["Call 999", "Donate blood at KNH", "Clear road access for ambulances"],
    evacuation_guidance: "Evacuate the immediate Kibera Market area. Go to Kibera Social Centre.",
    public_safety_message: "Stay clear of Kibera Market area. Emergency services are responding.",
    districts: ["Kibera", "Langata"],
    radius_km: 5,
    lat: -1.3133,
    lng: 36.7897,
  },
  {
    id: "alrt-003",
    title: "AI ALERT — Water Contamination Risk",
    message_en: "AI analysis detected water contamination spread pattern in Mathare Valley. Do not use tap water.",
    message_sw: "Uchambuzi wa AI uligundua mfumo wa kuenea kwa uchafuzi wa maji katika Bonde la Mathare.",
    severity: "high", category: "public_health",
    issued_at: "2026-06-27T08:15:00Z",
    affected_areas: ["Mathare", "Huruma", "Mwiki"],
    source: "Sentinel AI System", ai_generated: true, active: true,
    notification_channels: ["dashboard", "websocket"],
    delivery_status: { dashboard: "delivered", websocket: "broadcast" },
    recommended_actions: ["Do not drink tap water", "Boil all water before use", "Report symptoms to health authorities"],
    evacuation_guidance: "No evacuation needed. Use bottled water only.",
    public_safety_message: "Do not use tap water in Mathare, Huruma, or Mwiki until further notice.",
    districts: ["Mathare"],
    radius_km: 5,
    lat: -1.2587,
    lng: 36.8649,
  },
  {
    id: "alrt-004",
    title: "ROAD CLOSURE — Ngong Road",
    message_en: "Ngong Road between Kilimani and Dagoretti Corner closed due to civil unrest.",
    severity: "medium", category: "civil_unrest",
    issued_at: "2026-06-27T08:05:00Z",
    affected_areas: ["Kilimani", "Dagoretti", "Ngong Road Corridor"],
    source: "Nairobi Traffic Marshals", ai_generated: false, active: true,
    notification_channels: ["dashboard"],
    delivery_status: { dashboard: "delivered" },
    recommended_actions: ["Use alternative routes", "Avoid Ngong Road", "Follow traffic marshal instructions"],
    evacuation_guidance: undefined,
    public_safety_message: "Ngong Road is closed. Use Waiyaki Way or Langata Road as alternatives.",
    districts: ["Kilimani", "Dagoretti"],
    radius_km: 2.5,
    lat: -1.2981,
    lng: 36.7751,
  },
];

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: "shlt-001", name: "Westlands Community Hall", type: "emergency_shelter",
    lat: -1.2670, lng: 36.8050, address: "Westlands Road, Nairobi",
    capacity: 500, current_occupancy: 234,
    amenities: ["beds", "water", "food", "medical", "wifi"],
    contact: "+254-20-4440000", status: "open",
    notes: "24-hr operation. Generator backup.",
  },
  {
    id: "shlt-002", name: "Kibera Social Centre", type: "emergency_shelter",
    lat: -1.3120, lng: 36.7900, address: "Olympic Estate, Kibera",
    capacity: 800, current_occupancy: 612,
    amenities: ["beds", "water", "food", "sanitation"],
    contact: "+254-20-5550111", status: "nearly_full",
    notes: "MSF medical team on-site.",
  },
  {
    id: "shlt-003", name: "Kenyatta National Hospital Triage", type: "medical_facility",
    lat: -1.3009, lng: 36.8063, address: "Hospital Road, Upper Hill",
    capacity: 200, current_occupancy: 145,
    amenities: ["emergency_medical", "surgery", "pharmacy", "ambulance"],
    contact: "+254-20-2726300", status: "open",
    notes: "Emergency triage activated.",
  },
  {
    id: "shlt-004", name: "Ruaraka Community Church", type: "emergency_shelter",
    lat: -1.2450, lng: 36.8700, address: "Ruaraka Road, Kasarani",
    capacity: 350, current_occupancy: 67,
    amenities: ["beds", "water", "food"],
    contact: "+254-722-334455", status: "open",
    notes: "Ample space available.",
  },
  {
    id: "shlt-005", name: "UNHCR Reception Centre", type: "refugee_support",
    lat: -1.2780, lng: 36.8150, address: "Chiromo Road, Westlands",
    capacity: 300, current_occupancy: 189,
    amenities: ["beds", "water", "food", "legal_aid", "wifi", "translation"],
    contact: "+254-20-7621234", status: "open",
    notes: "Multilingual staff available.",
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "res-001", resource_type: "rescue_team",
    name: "Kenya Red Cross Rapid Response Unit A",
    description: "12-person search and rescue team with water rescue capability",
    quantity: 12, unit: "persons", status: "deployed",
    owner_org: "Kenya Red Cross", contact: "+254-20-3950000",
    lat: -1.2697, lng: 36.8134, location_name: "Westlands Underpass, Nairobi",
    assigned_incident_id: "inc-001",
    deployment_notes: "Deployed to Westlands flood response",
    created_at: "2026-06-27T06:00:00Z", updated_at: "2026-06-27T06:45:00Z",
    tags: ["water-rescue", "rapid-response"],
  },
  {
    id: "res-002", resource_type: "medical",
    name: "MSF Emergency Medical Kit — Alpha",
    description: "Full trauma and surgical kit for mass casualty events",
    quantity: 1, unit: "kit", status: "deployed",
    owner_org: "MSF Kenya", contact: "+254-722-100200",
    lat: -1.3133, lng: 36.7897, location_name: "Kibera Market, Nairobi",
    assigned_incident_id: "inc-002",
    deployment_notes: "Supporting Kibera gas explosion response",
    created_at: "2026-06-27T05:30:00Z", updated_at: "2026-06-27T06:00:00Z",
    tags: ["trauma", "surgical"],
  },
  {
    id: "res-003", resource_type: "water",
    name: "Water Purification Unit — Portable",
    description: "Portable water purification producing up to 5,000L/day",
    quantity: 2, unit: "units", status: "available",
    owner_org: "Nairobi Water & Sewerage", contact: "+254-20-3318000",
    lat: -1.2860, lng: 36.8219, location_name: "NWSC Depot, CBD",
    created_at: "2026-06-27T07:00:00Z", updated_at: "2026-06-27T07:00:00Z",
    tags: ["clean-water", "portable"],
  },
  {
    id: "res-004", resource_type: "food",
    name: "Emergency Food Rations — Batch 7",
    description: "5,000 ready-to-eat meal packs",
    quantity: 5000, unit: "packs", status: "available",
    owner_org: "WFP Kenya", contact: "+254-20-7621000",
    lat: -1.2880, lng: 36.8190, location_name: "Uhuru Park Distribution Point",
    created_at: "2026-06-27T07:30:00Z", updated_at: "2026-06-27T07:30:00Z",
    tags: ["ready-to-eat", "non-perishable"],
  },
  {
    id: "res-005", resource_type: "vehicle",
    name: "NDMA Heavy Rescue Truck Fleet",
    description: "3 heavy-duty rescue trucks with crane capability",
    quantity: 3, unit: "vehicles", status: "available",
    owner_org: "NDMA", contact: "+254-20-2710000",
    lat: -1.2830, lng: 36.8320, location_name: "NDMA Depot, Upperhill",
    created_at: "2026-06-27T06:00:00Z", updated_at: "2026-06-27T06:00:00Z",
    tags: ["heavy-rescue", "crane"],
  },
  {
    id: "res-006", resource_type: "volunteer",
    name: "St. John Ambulance Volunteer Corps",
    description: "Trained first-aid volunteers",
    quantity: 45, unit: "persons", status: "available",
    owner_org: "St. John Ambulance Kenya", contact: "+254-20-2229000",
    lat: -1.2921, lng: 36.8219, location_name: "CBD Staging Area",
    created_at: "2026-06-27T07:00:00Z", updated_at: "2026-06-27T07:00:00Z",
    tags: ["first-aid", "volunteer"],
  },
  {
    id: "res-007", resource_type: "shelter",
    name: "Emergency Tent Cluster — Mathare",
    description: "20 large tents for up to 200 persons",
    quantity: 20, unit: "tents", status: "deployed",
    owner_org: "UNHCR Kenya", contact: "+254-20-7621234",
    lat: -1.2587, lng: 36.8649, location_name: "Mathare Valley Open Ground",
    assigned_incident_id: "inc-003",
    deployment_notes: "Supporting water contamination displacement",
    created_at: "2026-06-27T08:00:00Z", updated_at: "2026-06-27T08:30:00Z",
    tags: ["temporary-shelter", "large-capacity"],
  },
  {
    id: "res-008", resource_type: "rescue_team",
    name: "NPS Disaster Response Unit B",
    description: "8-person National Police Service disaster response team",
    quantity: 8, unit: "persons", status: "available",
    owner_org: "National Police Service", contact: "+254-20-3456789",
    lat: -1.2750, lng: 36.8310, location_name: "Central Police Station, CBD",
    created_at: "2026-06-27T06:30:00Z", updated_at: "2026-06-27T06:30:00Z",
    tags: ["law-enforcement", "disaster-response"],
  },
];

export const MOCK_RESOURCE_REQUESTS: ResourceRequest[] = [
  {
    id: "req-001",
    requester_name: "Mary Akinyi",
    requester_phone: "+254-722-001122",
    requester_location: "Mathare Valley, Block C",
    lat: -1.2600, lng: 36.8660,
    category: "water",
    quantity_needed: 50,
    description: "Tap water contaminated. 50 families need clean water urgently.",
    incident_id: "inc-003",
    urgency: "critical",
    status: "acknowledged",
    created_at: "2026-06-27T09:00:00Z",
    updated_at: "2026-06-27T09:15:00Z",
  },
  {
    id: "req-002",
    requester_name: "Peter Kamau",
    requester_phone: "+254-733-445566",
    requester_location: "Kibera, Olympic Estate",
    lat: -1.3150, lng: 36.7890,
    category: "medical",
    quantity_needed: 1,
    description: "3 injured persons from gas explosion. Need medical assistance.",
    incident_id: "inc-002",
    urgency: "critical",
    status: "in_progress",
    fulfilled_by_resource_id: "res-002",
    responder_notes: "MSF team en route",
    created_at: "2026-06-27T06:00:00Z",
    updated_at: "2026-06-27T06:10:00Z",
  },
  {
    id: "req-003",
    requester_name: "Grace Njeri",
    requester_phone: "+254-710-778899",
    requester_location: "Westlands, Chiromo Road",
    lat: -1.2710, lng: 36.8100,
    category: "shelter",
    quantity_needed: 4,
    description: "Family of 4 displaced by flooding. Need temporary shelter.",
    incident_id: "inc-001",
    urgency: "high",
    status: "pending",
    created_at: "2026-06-27T07:30:00Z",
    updated_at: "2026-06-27T07:30:00Z",
  },
  {
    id: "req-004",
    requester_name: "David Ochieng",
    requester_phone: "+254-700-112233",
    requester_location: "Embakasi, Phase 5",
    lat: -1.3200, lng: 36.8800,
    category: "food",
    quantity_needed: 20,
    description: "20 elderly residents stranded without food for 2 days.",
    urgency: "high",
    status: "pending",
    created_at: "2026-06-27T10:00:00Z",
    updated_at: "2026-06-27T10:00:00Z",
  },
];
